-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 5.8
--C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n fifodc_w128x256_r64 -lang vhdl -synth synplify -bus_exp 7 -bb -arch sa5p00 -type ebfifo -depth 256 -width 128 -rwidth 64 -reset_rel SYNC -pe -1 -pf -1 -rfill -fill -fdc C:/lattice/LimeSDR-Mini_GW/LimeSDR-Mini_lms7_trx/proj/ip/fifo_dc/fifodc_w128x256_r64/fifodc_w128x256_r64.fdc 

-- Sat Feb 26 17:44:49 2022

library IEEE;
use IEEE.std_logic_1164.all;
library ECP5U;
use ECP5U.components.all;

entity fifodc_w128x256_r64 is
    port (
        Data: in  std_logic_vector(127 downto 0); 
        WrClock: in  std_logic; 
        RdClock: in  std_logic; 
        WrEn: in  std_logic; 
        RdEn: in  std_logic; 
        Reset: in  std_logic; 
        RPReset: in  std_logic; 
        Q: out  std_logic_vector(63 downto 0); 
        WCNT: out  std_logic_vector(8 downto 0); 
        RCNT: out  std_logic_vector(9 downto 0); 
        Empty: out  std_logic; 
        Full: out  std_logic);
end fifodc_w128x256_r64;

architecture Structure of fifodc_w128x256_r64 is

    -- internal signal declarations
    signal invout_1: std_logic;
    signal invout_0: std_logic;
    signal w_g2b_xor_cluster_1: std_logic;
    signal rcount_w0: std_logic;
    signal r_g2b_xor_cluster_1: std_logic;
    signal w_gdata_0: std_logic;
    signal w_gdata_1: std_logic;
    signal w_gdata_2: std_logic;
    signal w_gdata_3: std_logic;
    signal w_gdata_4: std_logic;
    signal w_gdata_5: std_logic;
    signal w_gdata_6: std_logic;
    signal w_gdata_7: std_logic;
    signal wptr_8: std_logic;
    signal r_gdata_0: std_logic;
    signal r_gdata_1: std_logic;
    signal r_gdata_2: std_logic;
    signal r_gdata_3: std_logic;
    signal r_gdata_4: std_logic;
    signal r_gdata_5: std_logic;
    signal r_gdata_6: std_logic;
    signal r_gdata_7: std_logic;
    signal r_gdata_8: std_logic;
    signal rptr_9: std_logic;
    signal w_gcount_0: std_logic;
    signal w_gcount_1: std_logic;
    signal w_gcount_2: std_logic;
    signal w_gcount_3: std_logic;
    signal w_gcount_4: std_logic;
    signal w_gcount_5: std_logic;
    signal w_gcount_6: std_logic;
    signal w_gcount_7: std_logic;
    signal w_gcount_8: std_logic;
    signal r_gcount_0: std_logic;
    signal r_gcount_1: std_logic;
    signal r_gcount_2: std_logic;
    signal r_gcount_3: std_logic;
    signal r_gcount_4: std_logic;
    signal r_gcount_5: std_logic;
    signal r_gcount_6: std_logic;
    signal r_gcount_7: std_logic;
    signal r_gcount_8: std_logic;
    signal r_gcount_9: std_logic;
    signal w_gcount_r20: std_logic;
    signal w_gcount_r0: std_logic;
    signal w_gcount_r21: std_logic;
    signal w_gcount_r1: std_logic;
    signal w_gcount_r22: std_logic;
    signal w_gcount_r2: std_logic;
    signal w_gcount_r23: std_logic;
    signal w_gcount_r3: std_logic;
    signal w_gcount_r24: std_logic;
    signal w_gcount_r4: std_logic;
    signal w_gcount_r25: std_logic;
    signal w_gcount_r5: std_logic;
    signal w_gcount_r26: std_logic;
    signal w_gcount_r6: std_logic;
    signal w_gcount_r27: std_logic;
    signal w_gcount_r7: std_logic;
    signal w_gcount_r28: std_logic;
    signal w_gcount_r8: std_logic;
    signal r_gcount_w20: std_logic;
    signal r_gcount_w0: std_logic;
    signal r_gcount_w21: std_logic;
    signal r_gcount_w1: std_logic;
    signal r_gcount_w22: std_logic;
    signal r_gcount_w2: std_logic;
    signal r_gcount_w23: std_logic;
    signal r_gcount_w3: std_logic;
    signal r_gcount_w24: std_logic;
    signal r_gcount_w4: std_logic;
    signal r_gcount_w25: std_logic;
    signal r_gcount_w5: std_logic;
    signal r_gcount_w26: std_logic;
    signal r_gcount_w6: std_logic;
    signal r_gcount_w27: std_logic;
    signal r_gcount_w7: std_logic;
    signal r_gcount_w28: std_logic;
    signal r_gcount_w8: std_logic;
    signal r_gcount_w29: std_logic;
    signal r_gcount_w9: std_logic;
    signal empty_i: std_logic;
    signal rRst: std_logic;
    signal full_i: std_logic;
    signal iwcount_0: std_logic;
    signal iwcount_1: std_logic;
    signal w_gctr_ci: std_logic;
    signal iwcount_2: std_logic;
    signal iwcount_3: std_logic;
    signal co0: std_logic;
    signal iwcount_4: std_logic;
    signal iwcount_5: std_logic;
    signal co1: std_logic;
    signal iwcount_6: std_logic;
    signal iwcount_7: std_logic;
    signal co2: std_logic;
    signal iwcount_8: std_logic;
    signal co4: std_logic;
    signal co3: std_logic;
    signal wcount_8: std_logic;
    signal ircount_0: std_logic;
    signal ircount_1: std_logic;
    signal r_gctr_ci: std_logic;
    signal ircount_2: std_logic;
    signal ircount_3: std_logic;
    signal co0_1: std_logic;
    signal ircount_4: std_logic;
    signal ircount_5: std_logic;
    signal co1_1: std_logic;
    signal ircount_6: std_logic;
    signal ircount_7: std_logic;
    signal co2_1: std_logic;
    signal ircount_8: std_logic;
    signal ircount_9: std_logic;
    signal co4_1: std_logic;
    signal co3_1: std_logic;
    signal rcount_9: std_logic;
    signal wfill_sub_0: std_logic;
    signal wptr_0: std_logic;
    signal precin: std_logic;
    signal wfill_sub_1: std_logic;
    signal wfill_sub_2: std_logic;
    signal wptr_2: std_logic;
    signal wptr_1: std_logic;
    signal co0_2: std_logic;
    signal wfill_sub_3: std_logic;
    signal wfill_sub_4: std_logic;
    signal wptr_4: std_logic;
    signal wptr_3: std_logic;
    signal co1_2: std_logic;
    signal wfill_sub_5: std_logic;
    signal wfill_sub_6: std_logic;
    signal wptr_6: std_logic;
    signal wptr_5: std_logic;
    signal co2_2: std_logic;
    signal wfill_sub_7: std_logic;
    signal wfill_sub_8: std_logic;
    signal wfill_sub_msb: std_logic;
    signal wptr_7: std_logic;
    signal co3_2: std_logic;
    signal co4_2d: std_logic;
    signal co4_2: std_logic;
    signal rfill_sub_0: std_logic;
    signal rptr_0: std_logic;
    signal precin_1: std_logic;
    signal rfill_sub_1: std_logic;
    signal rfill_sub_2: std_logic;
    signal rptr_2: std_logic;
    signal rptr_1: std_logic;
    signal co0_3: std_logic;
    signal rfill_sub_3: std_logic;
    signal rfill_sub_4: std_logic;
    signal rptr_4: std_logic;
    signal rptr_3: std_logic;
    signal co1_3: std_logic;
    signal rfill_sub_5: std_logic;
    signal rfill_sub_6: std_logic;
    signal rptr_6: std_logic;
    signal rptr_5: std_logic;
    signal co2_3: std_logic;
    signal rfill_sub_7: std_logic;
    signal rfill_sub_8: std_logic;
    signal rptr_8: std_logic;
    signal rptr_7: std_logic;
    signal co3_3: std_logic;
    signal rfill_sub_9: std_logic;
    signal rfill_sub_msb: std_logic;
    signal co4_3: std_logic;
    signal rden_i: std_logic;
    signal cmp_ci: std_logic;
    signal wcount_r0: std_logic;
    signal rcount_0: std_logic;
    signal rcount_1: std_logic;
    signal co0_4: std_logic;
    signal wcount_r1: std_logic;
    signal wcount_r2: std_logic;
    signal rcount_2: std_logic;
    signal rcount_3: std_logic;
    signal co1_4: std_logic;
    signal wcount_r3: std_logic;
    signal wcount_r4: std_logic;
    signal rcount_4: std_logic;
    signal rcount_5: std_logic;
    signal co2_4: std_logic;
    signal w_g2b_xor_cluster_0: std_logic;
    signal wcount_r6: std_logic;
    signal rcount_6: std_logic;
    signal rcount_7: std_logic;
    signal co3_4: std_logic;
    signal wcount_r7: std_logic;
    signal empty_cmp_clr: std_logic;
    signal rcount_8: std_logic;
    signal empty_cmp_set: std_logic;
    signal empty_d: std_logic;
    signal empty_d_c: std_logic;
    signal wren_i: std_logic;
    signal cmp_ci_1: std_logic;
    signal rcount_w1: std_logic;
    signal rcount_w2: std_logic;
    signal wcount_0: std_logic;
    signal wcount_1: std_logic;
    signal co0_5: std_logic;
    signal rcount_w3: std_logic;
    signal rcount_w4: std_logic;
    signal wcount_2: std_logic;
    signal wcount_3: std_logic;
    signal co1_5: std_logic;
    signal rcount_w5: std_logic;
    signal r_g2b_xor_cluster_0: std_logic;
    signal wcount_4: std_logic;
    signal wcount_5: std_logic;
    signal co2_5: std_logic;
    signal rcount_w7: std_logic;
    signal rcount_w8: std_logic;
    signal wcount_6: std_logic;
    signal wcount_7: std_logic;
    signal co3_5: std_logic;
    signal full_cmp_clr: std_logic;
    signal full_cmp_set: std_logic;
    signal full_d: std_logic;
    signal scuba_vhi: std_logic;
    signal scuba_vlo: std_logic;
    signal full_d_c: std_logic;

    attribute MEM_LPC_FILE : string; 
    attribute MEM_INIT_FILE : string; 
    attribute GSR : string; 
    attribute MEM_LPC_FILE of pdp_ram_0_0_3 : label is "fifodc_w128x256_r64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_0_3 : label is "";
    attribute MEM_LPC_FILE of pdp_ram_0_1_2 : label is "fifodc_w128x256_r64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_1_2 : label is "";
    attribute MEM_LPC_FILE of pdp_ram_0_2_1 : label is "fifodc_w128x256_r64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_2_1 : label is "";
    attribute MEM_LPC_FILE of pdp_ram_0_3_0 : label is "fifodc_w128x256_r64.lpc";
    attribute MEM_INIT_FILE of pdp_ram_0_3_0 : label is "";
    attribute GSR of FF_115 : label is "ENABLED";
    attribute GSR of FF_114 : label is "ENABLED";
    attribute GSR of FF_113 : label is "ENABLED";
    attribute GSR of FF_112 : label is "ENABLED";
    attribute GSR of FF_111 : label is "ENABLED";
    attribute GSR of FF_110 : label is "ENABLED";
    attribute GSR of FF_109 : label is "ENABLED";
    attribute GSR of FF_108 : label is "ENABLED";
    attribute GSR of FF_107 : label is "ENABLED";
    attribute GSR of FF_106 : label is "ENABLED";
    attribute GSR of FF_105 : label is "ENABLED";
    attribute GSR of FF_104 : label is "ENABLED";
    attribute GSR of FF_103 : label is "ENABLED";
    attribute GSR of FF_102 : label is "ENABLED";
    attribute GSR of FF_101 : label is "ENABLED";
    attribute GSR of FF_100 : label is "ENABLED";
    attribute GSR of FF_99 : label is "ENABLED";
    attribute GSR of FF_98 : label is "ENABLED";
    attribute GSR of FF_97 : label is "ENABLED";
    attribute GSR of FF_96 : label is "ENABLED";
    attribute GSR of FF_95 : label is "ENABLED";
    attribute GSR of FF_94 : label is "ENABLED";
    attribute GSR of FF_93 : label is "ENABLED";
    attribute GSR of FF_92 : label is "ENABLED";
    attribute GSR of FF_91 : label is "ENABLED";
    attribute GSR of FF_90 : label is "ENABLED";
    attribute GSR of FF_89 : label is "ENABLED";
    attribute GSR of FF_88 : label is "ENABLED";
    attribute GSR of FF_87 : label is "ENABLED";
    attribute GSR of FF_86 : label is "ENABLED";
    attribute GSR of FF_85 : label is "ENABLED";
    attribute GSR of FF_84 : label is "ENABLED";
    attribute GSR of FF_83 : label is "ENABLED";
    attribute GSR of FF_82 : label is "ENABLED";
    attribute GSR of FF_81 : label is "ENABLED";
    attribute GSR of FF_80 : label is "ENABLED";
    attribute GSR of FF_79 : label is "ENABLED";
    attribute GSR of FF_78 : label is "ENABLED";
    attribute GSR of FF_77 : label is "ENABLED";
    attribute GSR of FF_76 : label is "ENABLED";
    attribute GSR of FF_75 : label is "ENABLED";
    attribute GSR of FF_74 : label is "ENABLED";
    attribute GSR of FF_73 : label is "ENABLED";
    attribute GSR of FF_72 : label is "ENABLED";
    attribute GSR of FF_71 : label is "ENABLED";
    attribute GSR of FF_70 : label is "ENABLED";
    attribute GSR of FF_69 : label is "ENABLED";
    attribute GSR of FF_68 : label is "ENABLED";
    attribute GSR of FF_67 : label is "ENABLED";
    attribute GSR of FF_66 : label is "ENABLED";
    attribute GSR of FF_65 : label is "ENABLED";
    attribute GSR of FF_64 : label is "ENABLED";
    attribute GSR of FF_63 : label is "ENABLED";
    attribute GSR of FF_62 : label is "ENABLED";
    attribute GSR of FF_61 : label is "ENABLED";
    attribute GSR of FF_60 : label is "ENABLED";
    attribute GSR of FF_59 : label is "ENABLED";
    attribute GSR of FF_58 : label is "ENABLED";
    attribute GSR of FF_57 : label is "ENABLED";
    attribute GSR of FF_56 : label is "ENABLED";
    attribute GSR of FF_55 : label is "ENABLED";
    attribute GSR of FF_54 : label is "ENABLED";
    attribute GSR of FF_53 : label is "ENABLED";
    attribute GSR of FF_52 : label is "ENABLED";
    attribute GSR of FF_51 : label is "ENABLED";
    attribute GSR of FF_50 : label is "ENABLED";
    attribute GSR of FF_49 : label is "ENABLED";
    attribute GSR of FF_48 : label is "ENABLED";
    attribute GSR of FF_47 : label is "ENABLED";
    attribute GSR of FF_46 : label is "ENABLED";
    attribute GSR of FF_45 : label is "ENABLED";
    attribute GSR of FF_44 : label is "ENABLED";
    attribute GSR of FF_43 : label is "ENABLED";
    attribute GSR of FF_42 : label is "ENABLED";
    attribute GSR of FF_41 : label is "ENABLED";
    attribute GSR of FF_40 : label is "ENABLED";
    attribute GSR of FF_39 : label is "ENABLED";
    attribute GSR of FF_38 : label is "ENABLED";
    attribute GSR of FF_37 : label is "ENABLED";
    attribute GSR of FF_36 : label is "ENABLED";
    attribute GSR of FF_35 : label is "ENABLED";
    attribute GSR of FF_34 : label is "ENABLED";
    attribute GSR of FF_33 : label is "ENABLED";
    attribute GSR of FF_32 : label is "ENABLED";
    attribute GSR of FF_31 : label is "ENABLED";
    attribute GSR of FF_30 : label is "ENABLED";
    attribute GSR of FF_29 : label is "ENABLED";
    attribute GSR of FF_28 : label is "ENABLED";
    attribute GSR of FF_27 : label is "ENABLED";
    attribute GSR of FF_26 : label is "ENABLED";
    attribute GSR of FF_25 : label is "ENABLED";
    attribute GSR of FF_24 : label is "ENABLED";
    attribute GSR of FF_23 : label is "ENABLED";
    attribute GSR of FF_22 : label is "ENABLED";
    attribute GSR of FF_21 : label is "ENABLED";
    attribute GSR of FF_20 : label is "ENABLED";
    attribute GSR of FF_19 : label is "ENABLED";
    attribute GSR of FF_18 : label is "ENABLED";
    attribute GSR of FF_17 : label is "ENABLED";
    attribute GSR of FF_16 : label is "ENABLED";
    attribute GSR of FF_15 : label is "ENABLED";
    attribute GSR of FF_14 : label is "ENABLED";
    attribute GSR of FF_13 : label is "ENABLED";
    attribute GSR of FF_12 : label is "ENABLED";
    attribute GSR of FF_11 : label is "ENABLED";
    attribute GSR of FF_10 : label is "ENABLED";
    attribute GSR of FF_9 : label is "ENABLED";
    attribute GSR of FF_8 : label is "ENABLED";
    attribute GSR of FF_7 : label is "ENABLED";
    attribute GSR of FF_6 : label is "ENABLED";
    attribute GSR of FF_5 : label is "ENABLED";
    attribute GSR of FF_4 : label is "ENABLED";
    attribute GSR of FF_3 : label is "ENABLED";
    attribute GSR of FF_2 : label is "ENABLED";
    attribute GSR of FF_1 : label is "ENABLED";
    attribute GSR of FF_0 : label is "ENABLED";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    AND2_t21: AND2
        port map (A=>WrEn, B=>invout_1, Z=>wren_i);

    INV_1: INV
        port map (A=>full_i, Z=>invout_1);

    AND2_t20: AND2
        port map (A=>RdEn, B=>invout_0, Z=>rden_i);

    INV_0: INV
        port map (A=>empty_i, Z=>invout_0);

    OR2_t19: OR2
        port map (A=>Reset, B=>RPReset, Z=>rRst);

    XOR2_t18: XOR2
        port map (A=>wcount_0, B=>wcount_1, Z=>w_gdata_0);

    XOR2_t17: XOR2
        port map (A=>wcount_1, B=>wcount_2, Z=>w_gdata_1);

    XOR2_t16: XOR2
        port map (A=>wcount_2, B=>wcount_3, Z=>w_gdata_2);

    XOR2_t15: XOR2
        port map (A=>wcount_3, B=>wcount_4, Z=>w_gdata_3);

    XOR2_t14: XOR2
        port map (A=>wcount_4, B=>wcount_5, Z=>w_gdata_4);

    XOR2_t13: XOR2
        port map (A=>wcount_5, B=>wcount_6, Z=>w_gdata_5);

    XOR2_t12: XOR2
        port map (A=>wcount_6, B=>wcount_7, Z=>w_gdata_6);

    XOR2_t11: XOR2
        port map (A=>wcount_7, B=>wcount_8, Z=>w_gdata_7);

    XOR2_t10: XOR2
        port map (A=>rcount_0, B=>rcount_1, Z=>r_gdata_0);

    XOR2_t9: XOR2
        port map (A=>rcount_1, B=>rcount_2, Z=>r_gdata_1);

    XOR2_t8: XOR2
        port map (A=>rcount_2, B=>rcount_3, Z=>r_gdata_2);

    XOR2_t7: XOR2
        port map (A=>rcount_3, B=>rcount_4, Z=>r_gdata_3);

    XOR2_t6: XOR2
        port map (A=>rcount_4, B=>rcount_5, Z=>r_gdata_4);

    XOR2_t5: XOR2
        port map (A=>rcount_5, B=>rcount_6, Z=>r_gdata_5);

    XOR2_t4: XOR2
        port map (A=>rcount_6, B=>rcount_7, Z=>r_gdata_6);

    XOR2_t3: XOR2
        port map (A=>rcount_7, B=>rcount_8, Z=>r_gdata_7);

    XOR2_t2: XOR2
        port map (A=>rcount_8, B=>rcount_9, Z=>r_gdata_8);

    LUT4_22: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r25, AD2=>w_gcount_r26, 
            AD1=>w_gcount_r27, AD0=>w_gcount_r28, 
            DO0=>w_g2b_xor_cluster_0);

    LUT4_21: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r21, AD2=>w_gcount_r22, 
            AD1=>w_gcount_r23, AD0=>w_gcount_r24, 
            DO0=>w_g2b_xor_cluster_1);

    LUT4_20: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r27, AD2=>w_gcount_r28, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>wcount_r7);

    LUT4_19: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r26, AD2=>w_gcount_r27, 
            AD1=>w_gcount_r28, AD0=>scuba_vlo, DO0=>wcount_r6);

    LUT4_18: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r24, AD2=>w_gcount_r25, 
            AD1=>w_gcount_r26, AD0=>wcount_r7, DO0=>wcount_r4);

    LUT4_17: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r23, AD2=>w_gcount_r24, 
            AD1=>w_gcount_r25, AD0=>wcount_r6, DO0=>wcount_r3);

    LUT4_16: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_gcount_r22, AD2=>w_gcount_r23, 
            AD1=>w_gcount_r24, AD0=>w_g2b_xor_cluster_0, DO0=>wcount_r2);

    LUT4_15: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>scuba_vlo, AD0=>scuba_vlo, DO0=>wcount_r1);

    LUT4_14: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>w_g2b_xor_cluster_0, AD2=>w_g2b_xor_cluster_1, 
            AD1=>w_gcount_r20, AD0=>scuba_vlo, DO0=>wcount_r0);

    LUT4_13: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w26, AD2=>r_gcount_w27, 
            AD1=>r_gcount_w28, AD0=>r_gcount_w29, 
            DO0=>r_g2b_xor_cluster_0);

    LUT4_12: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w22, AD2=>r_gcount_w23, 
            AD1=>r_gcount_w24, AD0=>r_gcount_w25, 
            DO0=>r_g2b_xor_cluster_1);

    LUT4_11: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w28, AD2=>r_gcount_w29, AD1=>scuba_vlo, 
            AD0=>scuba_vlo, DO0=>rcount_w8);

    LUT4_10: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w27, AD2=>r_gcount_w28, 
            AD1=>r_gcount_w29, AD0=>scuba_vlo, DO0=>rcount_w7);

    LUT4_9: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w25, AD2=>r_gcount_w26, 
            AD1=>r_gcount_w27, AD0=>rcount_w8, DO0=>rcount_w5);

    LUT4_8: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w24, AD2=>r_gcount_w25, 
            AD1=>r_gcount_w26, AD0=>rcount_w7, DO0=>rcount_w4);

    LUT4_7: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_gcount_w23, AD2=>r_gcount_w24, 
            AD1=>r_gcount_w25, AD0=>r_g2b_xor_cluster_0, DO0=>rcount_w3);

    LUT4_6: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>scuba_vlo, AD0=>scuba_vlo, DO0=>rcount_w2);

    LUT4_5: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_gcount_w21, AD0=>scuba_vlo, DO0=>rcount_w1);

    LUT4_4: ROM16X1A
        generic map (initval=> X"6996")
        port map (AD3=>r_g2b_xor_cluster_0, AD2=>r_g2b_xor_cluster_1, 
            AD1=>r_gcount_w20, AD0=>r_gcount_w21, DO0=>rcount_w0);

    XOR2_t1: XOR2
        port map (A=>wptr_8, B=>r_gcount_w29, Z=>wfill_sub_msb);

    XOR2_t0: XOR2
        port map (A=>w_gcount_r28, B=>rptr_9, Z=>rfill_sub_msb);

    LUT4_3: ROM16X1A
        generic map (initval=> X"0410")
        port map (AD3=>rptr_9, AD2=>rcount_9, AD1=>w_gcount_r28, 
            AD0=>scuba_vlo, DO0=>empty_cmp_set);

    LUT4_2: ROM16X1A
        generic map (initval=> X"1004")
        port map (AD3=>rptr_9, AD2=>rcount_9, AD1=>w_gcount_r28, 
            AD0=>scuba_vlo, DO0=>empty_cmp_clr);

    LUT4_1: ROM16X1A
        generic map (initval=> X"0140")
        port map (AD3=>wptr_8, AD2=>wcount_8, AD1=>r_gcount_w29, 
            AD0=>scuba_vlo, DO0=>full_cmp_set);

    LUT4_0: ROM16X1A
        generic map (initval=> X"4001")
        port map (AD3=>wptr_8, AD2=>wcount_8, AD1=>r_gcount_w29, 
            AD0=>scuba_vlo, DO0=>full_cmp_clr);

    pdp_ram_0_0_3: PDPW16KD
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        CSDECODE_R=> "0b000", CSDECODE_W=> "0b001", GSR=> "ENABLED", 
        RESETMODE=> "ASYNC", REGMODE=> "NOREG", DATA_WIDTH_R=>  18, 
        DATA_WIDTH_W=>  36)
        port map (DI35=>Data(81), DI34=>Data(80), DI33=>Data(79), 
            DI32=>Data(78), DI31=>Data(77), DI30=>Data(76), 
            DI29=>Data(75), DI28=>Data(74), DI27=>Data(73), 
            DI26=>Data(72), DI25=>Data(71), DI24=>Data(70), 
            DI23=>Data(69), DI22=>Data(68), DI21=>Data(67), 
            DI20=>Data(66), DI19=>Data(65), DI18=>Data(64), 
            DI17=>Data(17), DI16=>Data(16), DI15=>Data(15), 
            DI14=>Data(14), DI13=>Data(13), DI12=>Data(12), 
            DI11=>Data(11), DI10=>Data(10), DI9=>Data(9), DI8=>Data(8), 
            DI7=>Data(7), DI6=>Data(6), DI5=>Data(5), DI4=>Data(4), 
            DI3=>Data(3), DI2=>Data(2), DI1=>Data(1), DI0=>Data(0), 
            ADW8=>scuba_vlo, ADW7=>wptr_7, ADW6=>wptr_6, ADW5=>wptr_5, 
            ADW4=>wptr_4, ADW3=>wptr_3, ADW2=>wptr_2, ADW1=>wptr_1, 
            ADW0=>wptr_0, BE3=>scuba_vhi, BE2=>scuba_vhi, BE1=>scuba_vhi, 
            BE0=>scuba_vhi, CEW=>wren_i, CLKW=>WrClock, CSW2=>scuba_vlo, 
            CSW1=>scuba_vlo, CSW0=>scuba_vhi, ADR13=>scuba_vlo, 
            ADR12=>rptr_8, ADR11=>rptr_7, ADR10=>rptr_6, ADR9=>rptr_5, 
            ADR8=>rptr_4, ADR7=>rptr_3, ADR6=>rptr_2, ADR5=>rptr_1, 
            ADR4=>rptr_0, ADR3=>scuba_vlo, ADR2=>scuba_vlo, 
            ADR1=>scuba_vlo, ADR0=>scuba_vlo, CER=>rden_i, OCER=>rden_i, 
            CLKR=>RdClock, CSR2=>scuba_vlo, CSR1=>scuba_vlo, 
            CSR0=>scuba_vlo, RST=>Reset, DO35=>open, DO34=>open, 
            DO33=>open, DO32=>open, DO31=>open, DO30=>open, DO29=>open, 
            DO28=>open, DO27=>open, DO26=>open, DO25=>open, DO24=>open, 
            DO23=>open, DO22=>open, DO21=>open, DO20=>open, DO19=>open, 
            DO18=>open, DO17=>Q(17), DO16=>Q(16), DO15=>Q(15), 
            DO14=>Q(14), DO13=>Q(13), DO12=>Q(12), DO11=>Q(11), 
            DO10=>Q(10), DO9=>Q(9), DO8=>Q(8), DO7=>Q(7), DO6=>Q(6), 
            DO5=>Q(5), DO4=>Q(4), DO3=>Q(3), DO2=>Q(2), DO1=>Q(1), 
            DO0=>Q(0));

    pdp_ram_0_1_2: PDPW16KD
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        CSDECODE_R=> "0b000", CSDECODE_W=> "0b001", GSR=> "ENABLED", 
        RESETMODE=> "ASYNC", REGMODE=> "NOREG", DATA_WIDTH_R=>  18, 
        DATA_WIDTH_W=>  36)
        port map (DI35=>Data(99), DI34=>Data(98), DI33=>Data(97), 
            DI32=>Data(96), DI31=>Data(95), DI30=>Data(94), 
            DI29=>Data(93), DI28=>Data(92), DI27=>Data(91), 
            DI26=>Data(90), DI25=>Data(89), DI24=>Data(88), 
            DI23=>Data(87), DI22=>Data(86), DI21=>Data(85), 
            DI20=>Data(84), DI19=>Data(83), DI18=>Data(82), 
            DI17=>Data(35), DI16=>Data(34), DI15=>Data(33), 
            DI14=>Data(32), DI13=>Data(31), DI12=>Data(30), 
            DI11=>Data(29), DI10=>Data(28), DI9=>Data(27), DI8=>Data(26), 
            DI7=>Data(25), DI6=>Data(24), DI5=>Data(23), DI4=>Data(22), 
            DI3=>Data(21), DI2=>Data(20), DI1=>Data(19), DI0=>Data(18), 
            ADW8=>scuba_vlo, ADW7=>wptr_7, ADW6=>wptr_6, ADW5=>wptr_5, 
            ADW4=>wptr_4, ADW3=>wptr_3, ADW2=>wptr_2, ADW1=>wptr_1, 
            ADW0=>wptr_0, BE3=>scuba_vhi, BE2=>scuba_vhi, BE1=>scuba_vhi, 
            BE0=>scuba_vhi, CEW=>wren_i, CLKW=>WrClock, CSW2=>scuba_vlo, 
            CSW1=>scuba_vlo, CSW0=>scuba_vhi, ADR13=>scuba_vlo, 
            ADR12=>rptr_8, ADR11=>rptr_7, ADR10=>rptr_6, ADR9=>rptr_5, 
            ADR8=>rptr_4, ADR7=>rptr_3, ADR6=>rptr_2, ADR5=>rptr_1, 
            ADR4=>rptr_0, ADR3=>scuba_vlo, ADR2=>scuba_vlo, 
            ADR1=>scuba_vlo, ADR0=>scuba_vlo, CER=>rden_i, OCER=>rden_i, 
            CLKR=>RdClock, CSR2=>scuba_vlo, CSR1=>scuba_vlo, 
            CSR0=>scuba_vlo, RST=>Reset, DO35=>open, DO34=>open, 
            DO33=>open, DO32=>open, DO31=>open, DO30=>open, DO29=>open, 
            DO28=>open, DO27=>open, DO26=>open, DO25=>open, DO24=>open, 
            DO23=>open, DO22=>open, DO21=>open, DO20=>open, DO19=>open, 
            DO18=>open, DO17=>Q(35), DO16=>Q(34), DO15=>Q(33), 
            DO14=>Q(32), DO13=>Q(31), DO12=>Q(30), DO11=>Q(29), 
            DO10=>Q(28), DO9=>Q(27), DO8=>Q(26), DO7=>Q(25), DO6=>Q(24), 
            DO5=>Q(23), DO4=>Q(22), DO3=>Q(21), DO2=>Q(20), DO1=>Q(19), 
            DO0=>Q(18));

    pdp_ram_0_2_1: PDPW16KD
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        CSDECODE_R=> "0b000", CSDECODE_W=> "0b001", GSR=> "ENABLED", 
        RESETMODE=> "ASYNC", REGMODE=> "NOREG", DATA_WIDTH_R=>  18, 
        DATA_WIDTH_W=>  36)
        port map (DI35=>Data(117), DI34=>Data(116), DI33=>Data(115), 
            DI32=>Data(114), DI31=>Data(113), DI30=>Data(112), 
            DI29=>Data(111), DI28=>Data(110), DI27=>Data(109), 
            DI26=>Data(108), DI25=>Data(107), DI24=>Data(106), 
            DI23=>Data(105), DI22=>Data(104), DI21=>Data(103), 
            DI20=>Data(102), DI19=>Data(101), DI18=>Data(100), 
            DI17=>Data(53), DI16=>Data(52), DI15=>Data(51), 
            DI14=>Data(50), DI13=>Data(49), DI12=>Data(48), 
            DI11=>Data(47), DI10=>Data(46), DI9=>Data(45), DI8=>Data(44), 
            DI7=>Data(43), DI6=>Data(42), DI5=>Data(41), DI4=>Data(40), 
            DI3=>Data(39), DI2=>Data(38), DI1=>Data(37), DI0=>Data(36), 
            ADW8=>scuba_vlo, ADW7=>wptr_7, ADW6=>wptr_6, ADW5=>wptr_5, 
            ADW4=>wptr_4, ADW3=>wptr_3, ADW2=>wptr_2, ADW1=>wptr_1, 
            ADW0=>wptr_0, BE3=>scuba_vhi, BE2=>scuba_vhi, BE1=>scuba_vhi, 
            BE0=>scuba_vhi, CEW=>wren_i, CLKW=>WrClock, CSW2=>scuba_vlo, 
            CSW1=>scuba_vlo, CSW0=>scuba_vhi, ADR13=>scuba_vlo, 
            ADR12=>rptr_8, ADR11=>rptr_7, ADR10=>rptr_6, ADR9=>rptr_5, 
            ADR8=>rptr_4, ADR7=>rptr_3, ADR6=>rptr_2, ADR5=>rptr_1, 
            ADR4=>rptr_0, ADR3=>scuba_vlo, ADR2=>scuba_vlo, 
            ADR1=>scuba_vlo, ADR0=>scuba_vlo, CER=>rden_i, OCER=>rden_i, 
            CLKR=>RdClock, CSR2=>scuba_vlo, CSR1=>scuba_vlo, 
            CSR0=>scuba_vlo, RST=>Reset, DO35=>open, DO34=>open, 
            DO33=>open, DO32=>open, DO31=>open, DO30=>open, DO29=>open, 
            DO28=>open, DO27=>open, DO26=>open, DO25=>open, DO24=>open, 
            DO23=>open, DO22=>open, DO21=>open, DO20=>open, DO19=>open, 
            DO18=>open, DO17=>Q(53), DO16=>Q(52), DO15=>Q(51), 
            DO14=>Q(50), DO13=>Q(49), DO12=>Q(48), DO11=>Q(47), 
            DO10=>Q(46), DO9=>Q(45), DO8=>Q(44), DO7=>Q(43), DO6=>Q(42), 
            DO5=>Q(41), DO4=>Q(40), DO3=>Q(39), DO2=>Q(38), DO1=>Q(37), 
            DO0=>Q(36));

    pdp_ram_0_3_0: PDPW16KD
        generic map (INIT_DATA=> "STATIC", ASYNC_RESET_RELEASE=> "SYNC", 
        CSDECODE_R=> "0b000", CSDECODE_W=> "0b001", GSR=> "ENABLED", 
        RESETMODE=> "ASYNC", REGMODE=> "NOREG", DATA_WIDTH_R=>  18, 
        DATA_WIDTH_W=>  36)
        port map (DI35=>scuba_vlo, DI34=>scuba_vlo, DI33=>scuba_vlo, 
            DI32=>scuba_vlo, DI31=>scuba_vlo, DI30=>scuba_vlo, 
            DI29=>scuba_vlo, DI28=>scuba_vlo, DI27=>Data(127), 
            DI26=>Data(126), DI25=>Data(125), DI24=>Data(124), 
            DI23=>Data(123), DI22=>Data(122), DI21=>Data(121), 
            DI20=>Data(120), DI19=>Data(119), DI18=>Data(118), 
            DI17=>scuba_vlo, DI16=>scuba_vlo, DI15=>scuba_vlo, 
            DI14=>scuba_vlo, DI13=>scuba_vlo, DI12=>scuba_vlo, 
            DI11=>scuba_vlo, DI10=>scuba_vlo, DI9=>Data(63), 
            DI8=>Data(62), DI7=>Data(61), DI6=>Data(60), DI5=>Data(59), 
            DI4=>Data(58), DI3=>Data(57), DI2=>Data(56), DI1=>Data(55), 
            DI0=>Data(54), ADW8=>scuba_vlo, ADW7=>wptr_7, ADW6=>wptr_6, 
            ADW5=>wptr_5, ADW4=>wptr_4, ADW3=>wptr_3, ADW2=>wptr_2, 
            ADW1=>wptr_1, ADW0=>wptr_0, BE3=>scuba_vhi, BE2=>scuba_vhi, 
            BE1=>scuba_vhi, BE0=>scuba_vhi, CEW=>wren_i, CLKW=>WrClock, 
            CSW2=>scuba_vlo, CSW1=>scuba_vlo, CSW0=>scuba_vhi, 
            ADR13=>scuba_vlo, ADR12=>rptr_8, ADR11=>rptr_7, 
            ADR10=>rptr_6, ADR9=>rptr_5, ADR8=>rptr_4, ADR7=>rptr_3, 
            ADR6=>rptr_2, ADR5=>rptr_1, ADR4=>rptr_0, ADR3=>scuba_vlo, 
            ADR2=>scuba_vlo, ADR1=>scuba_vlo, ADR0=>scuba_vlo, 
            CER=>rden_i, OCER=>rden_i, CLKR=>RdClock, CSR2=>scuba_vlo, 
            CSR1=>scuba_vlo, CSR0=>scuba_vlo, RST=>Reset, DO35=>open, 
            DO34=>open, DO33=>open, DO32=>open, DO31=>open, DO30=>open, 
            DO29=>open, DO28=>open, DO27=>open, DO26=>open, DO25=>open, 
            DO24=>open, DO23=>open, DO22=>open, DO21=>open, DO20=>open, 
            DO19=>open, DO18=>open, DO17=>open, DO16=>open, DO15=>open, 
            DO14=>open, DO13=>open, DO12=>open, DO11=>open, DO10=>open, 
            DO9=>Q(63), DO8=>Q(62), DO7=>Q(61), DO6=>Q(60), DO5=>Q(59), 
            DO4=>Q(58), DO3=>Q(57), DO2=>Q(56), DO1=>Q(55), DO0=>Q(54));

    FF_115: FD1P3BX
        port map (D=>iwcount_0, SP=>wren_i, CK=>WrClock, PD=>Reset, 
            Q=>wcount_0);

    FF_114: FD1P3DX
        port map (D=>iwcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_1);

    FF_113: FD1P3DX
        port map (D=>iwcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_2);

    FF_112: FD1P3DX
        port map (D=>iwcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_3);

    FF_111: FD1P3DX
        port map (D=>iwcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_4);

    FF_110: FD1P3DX
        port map (D=>iwcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_5);

    FF_109: FD1P3DX
        port map (D=>iwcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_6);

    FF_108: FD1P3DX
        port map (D=>iwcount_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_7);

    FF_107: FD1P3DX
        port map (D=>iwcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wcount_8);

    FF_106: FD1P3DX
        port map (D=>w_gdata_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_0);

    FF_105: FD1P3DX
        port map (D=>w_gdata_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_1);

    FF_104: FD1P3DX
        port map (D=>w_gdata_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_2);

    FF_103: FD1P3DX
        port map (D=>w_gdata_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_3);

    FF_102: FD1P3DX
        port map (D=>w_gdata_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_4);

    FF_101: FD1P3DX
        port map (D=>w_gdata_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_5);

    FF_100: FD1P3DX
        port map (D=>w_gdata_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_6);

    FF_99: FD1P3DX
        port map (D=>w_gdata_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_7);

    FF_98: FD1P3DX
        port map (D=>wcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>w_gcount_8);

    FF_97: FD1P3DX
        port map (D=>wcount_0, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_0);

    FF_96: FD1P3DX
        port map (D=>wcount_1, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_1);

    FF_95: FD1P3DX
        port map (D=>wcount_2, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_2);

    FF_94: FD1P3DX
        port map (D=>wcount_3, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_3);

    FF_93: FD1P3DX
        port map (D=>wcount_4, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_4);

    FF_92: FD1P3DX
        port map (D=>wcount_5, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_5);

    FF_91: FD1P3DX
        port map (D=>wcount_6, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_6);

    FF_90: FD1P3DX
        port map (D=>wcount_7, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_7);

    FF_89: FD1P3DX
        port map (D=>wcount_8, SP=>wren_i, CK=>WrClock, CD=>Reset, 
            Q=>wptr_8);

    FF_88: FD1P3BX
        port map (D=>ircount_0, SP=>rden_i, CK=>RdClock, PD=>rRst, 
            Q=>rcount_0);

    FF_87: FD1P3DX
        port map (D=>ircount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_1);

    FF_86: FD1P3DX
        port map (D=>ircount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_2);

    FF_85: FD1P3DX
        port map (D=>ircount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_3);

    FF_84: FD1P3DX
        port map (D=>ircount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_4);

    FF_83: FD1P3DX
        port map (D=>ircount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_5);

    FF_82: FD1P3DX
        port map (D=>ircount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_6);

    FF_81: FD1P3DX
        port map (D=>ircount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_7);

    FF_80: FD1P3DX
        port map (D=>ircount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_8);

    FF_79: FD1P3DX
        port map (D=>ircount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rcount_9);

    FF_78: FD1P3DX
        port map (D=>r_gdata_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_0);

    FF_77: FD1P3DX
        port map (D=>r_gdata_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_1);

    FF_76: FD1P3DX
        port map (D=>r_gdata_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_2);

    FF_75: FD1P3DX
        port map (D=>r_gdata_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_3);

    FF_74: FD1P3DX
        port map (D=>r_gdata_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_4);

    FF_73: FD1P3DX
        port map (D=>r_gdata_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_5);

    FF_72: FD1P3DX
        port map (D=>r_gdata_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_6);

    FF_71: FD1P3DX
        port map (D=>r_gdata_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_7);

    FF_70: FD1P3DX
        port map (D=>r_gdata_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_8);

    FF_69: FD1P3DX
        port map (D=>rcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>r_gcount_9);

    FF_68: FD1P3DX
        port map (D=>rcount_0, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_0);

    FF_67: FD1P3DX
        port map (D=>rcount_1, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_1);

    FF_66: FD1P3DX
        port map (D=>rcount_2, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_2);

    FF_65: FD1P3DX
        port map (D=>rcount_3, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_3);

    FF_64: FD1P3DX
        port map (D=>rcount_4, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_4);

    FF_63: FD1P3DX
        port map (D=>rcount_5, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_5);

    FF_62: FD1P3DX
        port map (D=>rcount_6, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_6);

    FF_61: FD1P3DX
        port map (D=>rcount_7, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_7);

    FF_60: FD1P3DX
        port map (D=>rcount_8, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_8);

    FF_59: FD1P3DX
        port map (D=>rcount_9, SP=>rden_i, CK=>RdClock, CD=>rRst, 
            Q=>rptr_9);

    FF_58: FD1S3DX
        port map (D=>w_gcount_0, CK=>RdClock, CD=>Reset, Q=>w_gcount_r0);

    FF_57: FD1S3DX
        port map (D=>w_gcount_1, CK=>RdClock, CD=>Reset, Q=>w_gcount_r1);

    FF_56: FD1S3DX
        port map (D=>w_gcount_2, CK=>RdClock, CD=>Reset, Q=>w_gcount_r2);

    FF_55: FD1S3DX
        port map (D=>w_gcount_3, CK=>RdClock, CD=>Reset, Q=>w_gcount_r3);

    FF_54: FD1S3DX
        port map (D=>w_gcount_4, CK=>RdClock, CD=>Reset, Q=>w_gcount_r4);

    FF_53: FD1S3DX
        port map (D=>w_gcount_5, CK=>RdClock, CD=>Reset, Q=>w_gcount_r5);

    FF_52: FD1S3DX
        port map (D=>w_gcount_6, CK=>RdClock, CD=>Reset, Q=>w_gcount_r6);

    FF_51: FD1S3DX
        port map (D=>w_gcount_7, CK=>RdClock, CD=>Reset, Q=>w_gcount_r7);

    FF_50: FD1S3DX
        port map (D=>w_gcount_8, CK=>RdClock, CD=>Reset, Q=>w_gcount_r8);

    FF_49: FD1S3DX
        port map (D=>r_gcount_0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w0);

    FF_48: FD1S3DX
        port map (D=>r_gcount_1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w1);

    FF_47: FD1S3DX
        port map (D=>r_gcount_2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w2);

    FF_46: FD1S3DX
        port map (D=>r_gcount_3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w3);

    FF_45: FD1S3DX
        port map (D=>r_gcount_4, CK=>WrClock, CD=>rRst, Q=>r_gcount_w4);

    FF_44: FD1S3DX
        port map (D=>r_gcount_5, CK=>WrClock, CD=>rRst, Q=>r_gcount_w5);

    FF_43: FD1S3DX
        port map (D=>r_gcount_6, CK=>WrClock, CD=>rRst, Q=>r_gcount_w6);

    FF_42: FD1S3DX
        port map (D=>r_gcount_7, CK=>WrClock, CD=>rRst, Q=>r_gcount_w7);

    FF_41: FD1S3DX
        port map (D=>r_gcount_8, CK=>WrClock, CD=>rRst, Q=>r_gcount_w8);

    FF_40: FD1S3DX
        port map (D=>r_gcount_9, CK=>WrClock, CD=>rRst, Q=>r_gcount_w9);

    FF_39: FD1S3DX
        port map (D=>w_gcount_r0, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r20);

    FF_38: FD1S3DX
        port map (D=>w_gcount_r1, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r21);

    FF_37: FD1S3DX
        port map (D=>w_gcount_r2, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r22);

    FF_36: FD1S3DX
        port map (D=>w_gcount_r3, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r23);

    FF_35: FD1S3DX
        port map (D=>w_gcount_r4, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r24);

    FF_34: FD1S3DX
        port map (D=>w_gcount_r5, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r25);

    FF_33: FD1S3DX
        port map (D=>w_gcount_r6, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r26);

    FF_32: FD1S3DX
        port map (D=>w_gcount_r7, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r27);

    FF_31: FD1S3DX
        port map (D=>w_gcount_r8, CK=>RdClock, CD=>Reset, 
            Q=>w_gcount_r28);

    FF_30: FD1S3DX
        port map (D=>r_gcount_w0, CK=>WrClock, CD=>rRst, Q=>r_gcount_w20);

    FF_29: FD1S3DX
        port map (D=>r_gcount_w1, CK=>WrClock, CD=>rRst, Q=>r_gcount_w21);

    FF_28: FD1S3DX
        port map (D=>r_gcount_w2, CK=>WrClock, CD=>rRst, Q=>r_gcount_w22);

    FF_27: FD1S3DX
        port map (D=>r_gcount_w3, CK=>WrClock, CD=>rRst, Q=>r_gcount_w23);

    FF_26: FD1S3DX
        port map (D=>r_gcount_w4, CK=>WrClock, CD=>rRst, Q=>r_gcount_w24);

    FF_25: FD1S3DX
        port map (D=>r_gcount_w5, CK=>WrClock, CD=>rRst, Q=>r_gcount_w25);

    FF_24: FD1S3DX
        port map (D=>r_gcount_w6, CK=>WrClock, CD=>rRst, Q=>r_gcount_w26);

    FF_23: FD1S3DX
        port map (D=>r_gcount_w7, CK=>WrClock, CD=>rRst, Q=>r_gcount_w27);

    FF_22: FD1S3DX
        port map (D=>r_gcount_w8, CK=>WrClock, CD=>rRst, Q=>r_gcount_w28);

    FF_21: FD1S3DX
        port map (D=>r_gcount_w9, CK=>WrClock, CD=>rRst, Q=>r_gcount_w29);

    FF_20: FD1S3DX
        port map (D=>wfill_sub_0, CK=>WrClock, CD=>Reset, Q=>WCNT(0));

    FF_19: FD1S3DX
        port map (D=>wfill_sub_1, CK=>WrClock, CD=>Reset, Q=>WCNT(1));

    FF_18: FD1S3DX
        port map (D=>wfill_sub_2, CK=>WrClock, CD=>Reset, Q=>WCNT(2));

    FF_17: FD1S3DX
        port map (D=>wfill_sub_3, CK=>WrClock, CD=>Reset, Q=>WCNT(3));

    FF_16: FD1S3DX
        port map (D=>wfill_sub_4, CK=>WrClock, CD=>Reset, Q=>WCNT(4));

    FF_15: FD1S3DX
        port map (D=>wfill_sub_5, CK=>WrClock, CD=>Reset, Q=>WCNT(5));

    FF_14: FD1S3DX
        port map (D=>wfill_sub_6, CK=>WrClock, CD=>Reset, Q=>WCNT(6));

    FF_13: FD1S3DX
        port map (D=>wfill_sub_7, CK=>WrClock, CD=>Reset, Q=>WCNT(7));

    FF_12: FD1S3DX
        port map (D=>wfill_sub_8, CK=>WrClock, CD=>Reset, Q=>WCNT(8));

    FF_11: FD1S3DX
        port map (D=>rfill_sub_0, CK=>RdClock, CD=>rRst, Q=>RCNT(0));

    FF_10: FD1S3DX
        port map (D=>rfill_sub_1, CK=>RdClock, CD=>rRst, Q=>RCNT(1));

    FF_9: FD1S3DX
        port map (D=>rfill_sub_2, CK=>RdClock, CD=>rRst, Q=>RCNT(2));

    FF_8: FD1S3DX
        port map (D=>rfill_sub_3, CK=>RdClock, CD=>rRst, Q=>RCNT(3));

    FF_7: FD1S3DX
        port map (D=>rfill_sub_4, CK=>RdClock, CD=>rRst, Q=>RCNT(4));

    FF_6: FD1S3DX
        port map (D=>rfill_sub_5, CK=>RdClock, CD=>rRst, Q=>RCNT(5));

    FF_5: FD1S3DX
        port map (D=>rfill_sub_6, CK=>RdClock, CD=>rRst, Q=>RCNT(6));

    FF_4: FD1S3DX
        port map (D=>rfill_sub_7, CK=>RdClock, CD=>rRst, Q=>RCNT(7));

    FF_3: FD1S3DX
        port map (D=>rfill_sub_8, CK=>RdClock, CD=>rRst, Q=>RCNT(8));

    FF_2: FD1S3DX
        port map (D=>rfill_sub_9, CK=>RdClock, CD=>rRst, Q=>RCNT(9));

    FF_1: FD1S3BX
        port map (D=>empty_d, CK=>RdClock, PD=>rRst, Q=>empty_i);

    FF_0: FD1S3DX
        port map (D=>full_d, CK=>WrClock, CD=>Reset, Q=>full_i);

    w_gctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>w_gctr_ci);

    w_gctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_0, A1=>wcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>w_gctr_ci, S0=>iwcount_0, S1=>iwcount_1, 
            COUT=>co0);

    w_gctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_2, A1=>wcount_3, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0, S0=>iwcount_2, S1=>iwcount_3, 
            COUT=>co1);

    w_gctr_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_4, A1=>wcount_5, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1, S0=>iwcount_4, S1=>iwcount_5, 
            COUT=>co2);

    w_gctr_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_6, A1=>wcount_7, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2, S0=>iwcount_6, S1=>iwcount_7, 
            COUT=>co3);

    w_gctr_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>wcount_8, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3, S0=>iwcount_8, S1=>open, COUT=>co4);

    r_gctr_cia: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vhi, B0=>scuba_vlo, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>r_gctr_ci);

    r_gctr_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_0, A1=>rcount_1, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>r_gctr_ci, S0=>ircount_0, S1=>ircount_1, 
            COUT=>co0_1);

    r_gctr_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_2, A1=>rcount_3, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_1, S0=>ircount_2, S1=>ircount_3, 
            COUT=>co1_1);

    r_gctr_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_4, A1=>rcount_5, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_1, S0=>ircount_4, S1=>ircount_5, 
            COUT=>co2_1);

    r_gctr_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_6, A1=>rcount_7, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_1, S0=>ircount_6, S1=>ircount_7, 
            COUT=>co3_1);

    r_gctr_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>rcount_8, A1=>rcount_9, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3_1, S0=>ircount_8, S1=>ircount_9, 
            COUT=>co4_1);

    precin_inst407: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"0000", 
        INIT0=> X"0000")
        port map (A0=>scuba_vhi, A1=>scuba_vhi, B0=>scuba_vhi, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>precin);

    wfill_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>scuba_vhi, A1=>wptr_0, B0=>scuba_vlo, 
            B1=>rcount_w1, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>precin, S0=>open, S1=>wfill_sub_0, 
            COUT=>co0_2);

    wfill_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wptr_1, A1=>wptr_2, B0=>rcount_w2, B1=>rcount_w3, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co0_2, S0=>wfill_sub_1, S1=>wfill_sub_2, COUT=>co1_2);

    wfill_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wptr_3, A1=>wptr_4, B0=>rcount_w4, B1=>rcount_w5, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co1_2, S0=>wfill_sub_3, S1=>wfill_sub_4, COUT=>co2_2);

    wfill_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wptr_5, A1=>wptr_6, B0=>r_g2b_xor_cluster_0, 
            B1=>rcount_w7, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_2, S0=>wfill_sub_5, S1=>wfill_sub_6, 
            COUT=>co3_2);

    wfill_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wptr_7, A1=>wfill_sub_msb, B0=>rcount_w8, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3_2, S0=>wfill_sub_7, S1=>wfill_sub_8, 
            COUT=>co4_2);

    wfilld: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co4_2, S0=>co4_2d, S1=>open, COUT=>open);

    precin_inst425: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"0000", 
        INIT0=> X"0000")
        port map (A0=>scuba_vhi, A1=>scuba_vhi, B0=>scuba_vhi, 
            B1=>scuba_vhi, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>'X', S0=>open, S1=>open, COUT=>precin_1);

    rfill_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>scuba_vhi, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>rptr_0, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>precin_1, S0=>open, S1=>rfill_sub_0, 
            COUT=>co0_3);

    rfill_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_r0, A1=>wcount_r1, B0=>rptr_1, B1=>rptr_2, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co0_3, S0=>rfill_sub_1, S1=>rfill_sub_2, COUT=>co1_3);

    rfill_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_r2, A1=>wcount_r3, B0=>rptr_3, B1=>rptr_4, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co1_3, S0=>rfill_sub_3, S1=>rfill_sub_4, COUT=>co2_3);

    rfill_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_r4, A1=>w_g2b_xor_cluster_0, B0=>rptr_5, 
            B1=>rptr_6, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_3, S0=>rfill_sub_5, S1=>rfill_sub_6, 
            COUT=>co3_3);

    rfill_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_r6, A1=>wcount_r7, B0=>rptr_7, B1=>rptr_8, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>co3_3, S0=>rfill_sub_7, S1=>rfill_sub_8, COUT=>co4_3);

    rfill_5: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rfill_sub_msb, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co4_3, S0=>rfill_sub_9, S1=>open, 
            COUT=>open);

    empty_cmp_ci_a: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>rden_i, B0=>scuba_vlo, B1=>rden_i, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>'X', S0=>open, S1=>open, COUT=>cmp_ci);

    empty_cmp_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_0, A1=>rcount_1, B0=>scuba_vlo, 
            B1=>wcount_r0, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>cmp_ci, S0=>open, S1=>open, COUT=>co0_4);

    empty_cmp_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_2, A1=>rcount_3, B0=>wcount_r1, 
            B1=>wcount_r2, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_4, S0=>open, S1=>open, COUT=>co1_4);

    empty_cmp_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_4, A1=>rcount_5, B0=>wcount_r3, 
            B1=>wcount_r4, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co1_4, S0=>open, S1=>open, COUT=>co2_4);

    empty_cmp_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_6, A1=>rcount_7, B0=>w_g2b_xor_cluster_0, 
            B1=>wcount_r6, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_4, S0=>open, S1=>open, COUT=>co3_4);

    empty_cmp_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>rcount_8, A1=>empty_cmp_set, B0=>wcount_r7, 
            B1=>empty_cmp_clr, C0=>scuba_vhi, C1=>scuba_vhi, 
            D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co3_4, S0=>open, S1=>open, 
            COUT=>empty_d_c);

    a0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>empty_d_c, S0=>empty_d, S1=>open, 
            COUT=>open);

    full_cmp_ci_a: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>wren_i, B0=>scuba_vlo, B1=>wren_i, 
            C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, D1=>scuba_vhi, 
            CIN=>'X', S0=>open, S1=>open, COUT=>cmp_ci_1);

    full_cmp_0: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_0, A1=>wcount_1, B0=>rcount_w1, 
            B1=>rcount_w2, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>cmp_ci_1, S0=>open, S1=>open, 
            COUT=>co0_5);

    full_cmp_1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_2, A1=>wcount_3, B0=>rcount_w3, 
            B1=>rcount_w4, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co0_5, S0=>open, S1=>open, COUT=>co1_5);

    full_cmp_2: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_4, A1=>wcount_5, B0=>rcount_w5, 
            B1=>r_g2b_xor_cluster_0, C0=>scuba_vhi, C1=>scuba_vhi, 
            D0=>scuba_vhi, D1=>scuba_vhi, CIN=>co1_5, S0=>open, S1=>open, 
            COUT=>co2_5);

    full_cmp_3: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>wcount_6, A1=>wcount_7, B0=>rcount_w7, 
            B1=>rcount_w8, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co2_5, S0=>open, S1=>open, COUT=>co3_5);

    full_cmp_4: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"99AA", 
        INIT0=> X"99AA")
        port map (A0=>full_cmp_set, A1=>scuba_vlo, B0=>full_cmp_clr, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>co3_5, S0=>open, S1=>open, 
            COUT=>full_d_c);

    scuba_vhi_inst: VHI
        port map (Z=>scuba_vhi);

    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    a1: CCU2C
        generic map (INJECT1_1=> "NO", INJECT1_0=> "NO", INIT1=> X"66AA", 
        INIT0=> X"66AA")
        port map (A0=>scuba_vlo, A1=>scuba_vlo, B0=>scuba_vlo, 
            B1=>scuba_vlo, C0=>scuba_vhi, C1=>scuba_vhi, D0=>scuba_vhi, 
            D1=>scuba_vhi, CIN=>full_d_c, S0=>full_d, S1=>open, 
            COUT=>open);

    Empty <= empty_i;
    Full <= full_i;
end Structure;
